[theme]
primaryColor = "#FFBE00"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#262730"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
